if(EXISTS "E:/DataStructures/ce205-final-eray-burak-cakir-cpp/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
  include("E:/DataStructures/ce205-final-eray-burak-cakir-cpp/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
