if(EXISTS "E:/DataStructures/ce205-final-eray-burak-cakir-cpp/build_win/src/tests/CarMaintenance/CarMaintenance_tests[1]_tests.cmake")
  include("E:/DataStructures/ce205-final-eray-burak-cakir-cpp/build_win/src/tests/CarMaintenance/CarMaintenance_tests[1]_tests.cmake")
else()
  add_test(CarMaintenance_tests_NOT_BUILT CarMaintenance_tests_NOT_BUILT)
endif()
